### ISSUE TITLE
throws : The super constructor to "inherits" must have a prototype

### ISSUE THREAD

**Issue by shalinlk** [winstonjs/winstond#6]
We have been trying to configure winstond with following simple conf : 

```
 var server = winstond.nssocket.createServer({
  services: ['collect', 'query', 'stream'],
  port: 9003
});

```
But it throws an exception :

TypeError: The super constructor to "inherits" must have a prototype
    at Object.inherits (util.js:973:11)
    at Object.<anonymous> (/Users/shalinlk/Projects/test/log-server/dist/node_modules/winstond/lib/winstond/server.js:29:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.Server (/Users/shalinlk/Projects/test/log-server/dist/node_modules/winstond/lib/winstond.js:8:10)
 
Also tried with http  :
```
var server = winstond.http.createServer({
  services: ['collect', 'query', 'stream'],
  port: 9003
});

``` 

returns the same error.

**Comment by kpounds81** [comment]
Been having this same issue as well with Winstond... 

But.... seeing as how this hasn't been updated in 6 years, I think we're wasting our time with winstond.

**Comment by frederik-b** [comment]
Same error here :(
